#pragma once

#include "ch32v20x.h"

/* CH32V203G6U6 minimal board schematic mapping. */
#define BOARD_HEARTBEAT_GPIO_PORT GPIOA
#define BOARD_HEARTBEAT_GPIO_PIN  GPIO_Pin_0
#define BOARD_HEARTBEAT_GPIO_CLK  RCC_APB2Periph_GPIOA
#define BOARD_HEARTBEAT_ACTIVE_LOW 0

#define BOARD_LED_GPIO_PORT      BOARD_HEARTBEAT_GPIO_PORT
#define BOARD_LED_GPIO_PIN       BOARD_HEARTBEAT_GPIO_PIN
#define BOARD_LED_GPIO_CLK       BOARD_HEARTBEAT_GPIO_CLK
#define BOARD_LED_ACTIVE_LOW     BOARD_HEARTBEAT_ACTIVE_LOW

#define BOARD_ADC0_GPIO_PORT     GPIOA
#define BOARD_ADC0_GPIO_PIN      GPIO_Pin_0
#define BOARD_ADC0_GPIO_CLK      RCC_APB2Periph_GPIOA
#define BOARD_ADC0_CHANNEL       ADC_Channel_0

#define BOARD_SPI1_CS_GPIO_PORT   GPIOA
#define BOARD_SPI1_CS_GPIO_PIN    GPIO_Pin_4
#define BOARD_SPI1_SCK_GPIO_PORT  GPIOA
#define BOARD_SPI1_SCK_GPIO_PIN   GPIO_Pin_5
#define BOARD_SPI1_MISO_GPIO_PORT GPIOA
#define BOARD_SPI1_MISO_GPIO_PIN  GPIO_Pin_6
#define BOARD_SPI1_MOSI_GPIO_PORT GPIOA
#define BOARD_SPI1_MOSI_GPIO_PIN  GPIO_Pin_7
#define BOARD_SPI1_GPIO_CLK       RCC_APB2Periph_GPIOA
#define BOARD_SPI1_INSTANCE       SPI1
#define BOARD_SPI1_CLK            RCC_APB2Periph_SPI1

#define BOARD_I2C1_SCL_GPIO_PORT GPIOB
#define BOARD_I2C1_SCL_GPIO_PIN  GPIO_Pin_6
#define BOARD_I2C1_SDA_GPIO_PORT GPIOB
#define BOARD_I2C1_SDA_GPIO_PIN  GPIO_Pin_7
#define BOARD_I2C1_GPIO_CLK      RCC_APB2Periph_GPIOB
#define BOARD_I2C1_INSTANCE      I2C1
#define BOARD_I2C1_CLK           RCC_APB1Periph_I2C1


#define BOARD_MPU6050_I2C_INSTANCE BOARD_I2C1_INSTANCE
#define BOARD_MPU6050_SCL_GPIO_PORT BOARD_I2C1_SCL_GPIO_PORT
#define BOARD_MPU6050_SCL_GPIO_PIN  BOARD_I2C1_SCL_GPIO_PIN
#define BOARD_MPU6050_SDA_GPIO_PORT BOARD_I2C1_SDA_GPIO_PORT
#define BOARD_MPU6050_SDA_GPIO_PIN  BOARD_I2C1_SDA_GPIO_PIN
#define BOARD_MPU6050_I2C_GPIO_CLK  BOARD_I2C1_GPIO_CLK
#define BOARD_MPU6050_I2C_CLK       BOARD_I2C1_CLK
#define BOARD_MPU6050_I2C_SPEED_HZ  100000U
#define BOARD_MPU6050_I2C_ADDR      0x68U

#define BOARD_VL53L0X_I2C_INSTANCE BOARD_I2C1_INSTANCE
#define BOARD_VL53L0X_SCL_GPIO_PORT BOARD_I2C1_SCL_GPIO_PORT
#define BOARD_VL53L0X_SCL_GPIO_PIN  BOARD_I2C1_SCL_GPIO_PIN
#define BOARD_VL53L0X_SDA_GPIO_PORT BOARD_I2C1_SDA_GPIO_PORT
#define BOARD_VL53L0X_SDA_GPIO_PIN  BOARD_I2C1_SDA_GPIO_PIN
#define BOARD_VL53L0X_I2C_GPIO_CLK  BOARD_I2C1_GPIO_CLK
#define BOARD_VL53L0X_I2C_CLK       BOARD_I2C1_CLK
#define BOARD_VL53L0X_I2C_SPEED_HZ  100000U
#define BOARD_VL53L0X_I2C_ADDR      0x29U

#define BOARD_UART_TX_GPIO_PORT  GPIOA
#define BOARD_UART_TX_GPIO_PIN   GPIO_Pin_9
#define BOARD_UART_RX_GPIO_PORT  GPIOA
#define BOARD_UART_RX_GPIO_PIN   GPIO_Pin_10
#define BOARD_UART_GPIO_CLK      RCC_APB2Periph_GPIOA
#define BOARD_UART_INSTANCE      USART1
#define BOARD_UART_CLK           RCC_APB2Periph_USART1

#define BOARD_CAN_RX_GPIO_PORT   GPIOA
#define BOARD_CAN_RX_GPIO_PIN    GPIO_Pin_11
#define BOARD_CAN_TX_GPIO_PORT   GPIOA
#define BOARD_CAN_TX_GPIO_PIN    GPIO_Pin_12
#define BOARD_CAN_GPIO_CLK       RCC_APB2Periph_GPIOA
#define BOARD_CAN_INSTANCE       CAN1
#define BOARD_CAN_CLK            RCC_APB1Periph_CAN1

#define BOARD_SWDIO_GPIO_PORT    GPIOA
#define BOARD_SWDIO_GPIO_PIN     GPIO_Pin_13
#define BOARD_SWCLK_GPIO_PORT    GPIOA
#define BOARD_SWCLK_GPIO_PIN     GPIO_Pin_14

